name: my_satellite_env  # Change this to your preferred environment name
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pyyaml
  - pytorch>=2.0.0
  - torchvision
  - xarray
  - bottleneck
  - timm
  - einops
  - yacs
  - affine
  - tqdm
  - wandb
  - pillow
  - rioxarray
  - geopandas
  - pandas
  - matplotlib
  - scipy
