model:
  name: "Prithvi_Global_aquaculture"
  n_channel: 6
  n_class: 4
  encoder_embed_dim: 1024
  dec_embed_dim: 512
  dropout_rate: 0.2
  arch: "prithvi"

device_name: "cuda"
#wandb_project: "Landsat-aquaculture-finetune-100prcnt-prithviGlobal"

n_iteration: 300

prithvi_model_new_weight: "/workspace/SamK/prithvi_v2/Prithvi_EO_V2_300M.pt"
#prithvi_model_new_weight: "/mnt/c/Users/samkh/OneDrive/third_paper/prithviV2/Prithvi_EO_V2_300M.pt"
#prithvi_model_new_weight: "/mnt/c/Users/samkh/OneDrive/third_paper/prithviV2/checkpoint.pt"

training:
  train_batch_size: 6
  learning_rate: 0.0001
  shuffle: True
  subset: 1

  freeze_backbone: False

  optimizer:
    name: "AdamW"
    params:
      lr: 0.0001
       

  scheduler:
    name: "StepLR"
    params:
      step_size: 10
      gamma: 0.9


validation:
  val_batch_size: 2
  shuffle: False

inference:
  inference_batch_size: 1
  shuffle: False
  pred_outdir: /workspace/SamK/prithvi_v2/results/5p_freeze/5p_freeze_ood_pred
  prithvi_finetune_weight: /workspace/SamK/prithvi_v2/results/5p_freeze/best_checkpoint.pt


data:
  #input: ['S1', 'S2']
  dataset_name: ood_pred_dataset
  n_frame: 1
  n_time_steps: 1
  data_dir: "/workspace/SamK/prithvi_v2/aquaculture_data"
  train_csv_path: /workspace/SamK/prithvi_v2/aquaculture_data/train_images_5p.csv
  val_csv_path: /workspace/SamK/prithvi_v2/aquaculture_data/val_images.csv
  #train_dir_input: "/rhome/rghosal/crop/training_chips"
  #val_dir_input: "/rhome/rghosal/crop/validation_chips"
  #train_annot: "/rhome/rghosal/crop/training_data.txt"
  #val_annot: "/rhome/rghosal/crop/validation_data.txt"
  apply_normalization: True
  global_stats:
    #mean: [0.120230265, 0.10370902, 0.08467793, 0.19951299, 0.109360956, 0.060086336]
    #std: [0.01318866, 0.016127938, 0.021753421, 0.07539786, 0.054378532, 0.035520297]
    
    # mean: [0.0558, 0.064634, 0.081967, 0.133313, 0.135670, 0.103967]
    # std: [0.034061, 0.048656, 0.072708, 0.117232, 0.134407, 0.106152]
    
    mean: [0.055916585, 0.07825676, 0.099485956, 0.17510535, 0.15318502, 0.11263158]
    std: [0.020870697, 0.0273139, 0.042786587, 0.08869097, 0.08902759, 0.069095954]
  
  input_size: [1, 224, 224]
  patch_size: [1, 16, 16]
  transformations:
  - v_flip
  - h_flip
  - d_flip
  - rotate
  #target_norm: "none"
  #input_norm: "zscore"
  
Loss: "CrossEntropyLoss"
class_weights:  [
    0.1295236564566017, 
    0.28468693695264996, 
    0.29059512003264765,
    0.2951942865581007
  ]

ignore_index: -100

output_dir: "/workspace/SamK/prithvi_v2/results/5p_noFrz_fairIter"
#output_dir: "/mnt/c/Users/samkh/OneDrive/third_paper/prithviV2/results/100p"

logging:
checkpoint_dir: "/workspace/SamK/prithvi_v2/results/chpt/checkpoint_aqa100_p.pth"
#checkpoint_dir: "/mnt/c/Users/samkh/OneDrive/third_paper/prithviV2/results/chpt/checkpoint_aqa100_p.pth"  

#segment_input_path: "/rhome/rghosal/crop/validation_chips/chip_304_542_merged.tif"
#predicted_mask_dir: "./segment_out_prithvi_crop"