model:
  name: "Prithvi_Global_aquaculture"
  n_channel: 6
  n_class: 4
  depth: 24    
  encoder_embed_dim: 1024    
  dec_embed_dim: 512
  dropout_rate: 0.2
  fpn1_type: "pixelshuffle"
  arch: "prithvi"

device_name: "cuda"
#wandb_project: "Landsat-aquaculture-finetune-100prcnt-prithviGlobal"

inference:
  inference_batch_size: 1
  shuffle: False
  pred_outdir:                # <-- add the path for prediction outputs (example: /mnt/c/My_documents/aquaculture_project/prithviV2/outpred)
  prithvi_finetune_weight:    # <-- add the path for loading finetuned model weights (example: /mnt/c/My_documents/aquaculture_project/prithviV2/finetuned_model.pt)


data:
  dataset_name: ID_pred_dataset 
  n_frame: 1
  n_time_steps: 1
  data_dir:  ""               #<-- direct to the proper path for inference dataset
  apply_normalization: True
  global_stats:
    # use with ID pred dataset
    mean: [0.120230265, 0.10370902, 0.08467793, 0.19951299, 0.109360956, 0.060086336]
    std: [0.01318866, 0.016127938, 0.021753421, 0.07539786, 0.054378532, 0.035520297]
  
  input_size: [1, 224, 224]
  patch_size: [1, 16, 16]    # [1, 16, 16] for 300M model and [1, 14, 14] for 600M

